<?php
return array (
  'db_type' => 'mysql',
  'db_host' => 'localhost',
  'db_name' => 'gxcms',
  'db_user' => 'root',
  'db_pwd' => 'dengjing4234',
  'db_port' => '3306',
  'db_prefix' => 'gx_',
  'default_theme' => 'default',
  'web_name' => '84影视网-大量高清电影电视剧动漫在线观看',
  'web_url' => 'http://www.84fun.com/',
  'web_path' => '/',
  'web_hotkey' => '福尔摩斯|美国恐怖故事|生活大爆炸|诉讼双雄|桃花期|合租屋的恋人|dinner',
  'web_keywords' => '在线电影,在线电视剧,高清电影,热门电影,最新电影在线观看,在线影片,国产剧,欧美大片,日剧,韩剧,美剧,偶像剧,台剧,港片,综艺节目',
  'web_description' => '84影视提供最新电视剧,2012最新电影,快播电影网,最新日剧,最新韩剧,香港TVB电视剧,台湾偶像剧的在线观看和下载,每天第一时间更新,高清不卡,无需缓冲,土豆网,优酷网,百度影音,QVOD快播多线路观看',
  'web_email' => 'dengjing34@vip.qq.com',
  'web_qq' => '35946360',
  'web_copyright' => '本网站提供的最新电视剧和电影资源均系收集于各大视频网站，本网站只提供web页面服务，并不提供影片资源存储，也不参与录制、上传。',
  'web_tongji' => '',
  'web_icp' => '',
  'web_adsensepath' => 'temp/Banner',
  'web_admin_pagenum' => 20,
  'web_home_pagenum' => '5',
  'web_admin_hits' => 0,
  'web_hits_way' => '0',
  'web_hits_time' => 5,
  'web_admin_updown' => 0,
  'web_admin_score' => 9,
  'web_collect_num' => 3,
  'web_admin_edittime' => false,
  'web_admin_ordertype' => 'id',
  'web_admin_language' => '国语,粤语,英语,韩语,日语,法语,中文字幕,英文字幕',
  'web_admin_area' => '中国,内地,香港,台湾,韩国,日本,美国,英国,法国,意大利,德国,西班牙,泰国',
  'web_admin_nav' => 
  array (
    '网站信息配置' => '?s=Admin/Config/Conf/id/web',
    '视频数据管理' => '?s=Admin/Video/Show',
    '影片采集中心' => '?s=Admin/Collect/Show',
    '网站栏目管理' => '?s=Admin/Channel/Show',
    '网站广告管理' => '?s=Admin/Adsense/Show',
    '快捷菜单设置' => '?s=Admin/Config/Conf/id/nav',
  ),
  'upload_path' => 'uploads',
  'upload_style' => 'Y-m-d',
  'upload_thumb' => '0',
  'upload_thumb_w' => 120,
  'upload_thumb_h' => 168,
  'upload_water' => '0',
  'upload_water_img' => 'views/images/water.gif',
  'upload_water_pct' => 80,
  'upload_water_pos' => 9,
  'upload_http_down' => 10,
  'upload_http' => '1',
  'upload_ftp' => '0',
  'upload_ftp_host' => '255.255.255.255',
  'upload_ftp_user' => 'username',
  'upload_ftp_pass' => 'userpwd',
  'upload_ftp_port' => 21,
  'upload_ftp_dir' => '/',
  'upload_ftp_url' => '',
  'tmpl_cache_on' => true,
  'html_cache_on' => true,
  'html_cache_time' => 0,
  'html_read_type' => 0,
  'html_cache_index' => 1,
  'html_cache_list' => 1,
  'html_cache_content' => 1,
  'html_cache_play' => 1,
  'html_cache_mytpl' => '1',
  'url_html_suffix' => '.html',
  'html_file_suffix' => '.html',
  'url_rewrite' => '1',
  'url_html' => '0',
  'url_html_rule' => '2',
  'url_html_channel' => '0',
  'url_html_play' => '0',
  'url_create_time' => 2,
  'url_create_num' => 30,
  'url_dir_video' => 'vodlist',
  'url_dir_videoread' => 'detail',
  'url_dir_videoplay' => 'play',
  'url_dir_info' => 'infolist',
  'url_dir_inforead' => 'detail-n',
  'url_dir_special' => 'special',
  'url_dir_maps' => 'maps',
  'url_dir_all' => '',
  'user_register' => '1',
  'user_comment' => '1',
  'user_check' => '1',
  'user_pay' => '0',
  'user_post' => '1',
  'user_paycid' => 
  array (
    0 => '8',
    1 => '9',
    2 => '10',
    3 => '11',
    4 => '12',
    5 => '13',
    6 => '14',
    7 => '15',
    8 => '16',
    9 => '17',
    10 => '18',
    11 => '19',
    12 => '20',
    13 => '21',
    14 => '3',
    15 => '5',
    16 => '6',
  ),
  'user_money_play' => 1,
  'user_money_change' => 100,
  'user_money_add' => 20,
  'user_check_time' => 60,
  'user_page_cm' => 8,
  'user_page_gb' => 10,
  'user_replace' => '脏话|法轮功|枪械|A片|三级|伦理',
  '_htmls_' => 
  array (
    'home:index:index' => 
    array (
      0 => '{:action}',
      1 => 3600,
    ),
    'home:video:lists' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:info:lists' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:video:detail' => 
    array (
      0 => '{:module}_{:action}/{id|md5}',
      1 => 3600,
    ),
    'home:info:detail' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
    'home:video:play' => 
    array (
      0 => '{:module}_{:action}/{id|md5}',
      1 => 3600,
    ),
    'home:my:show' => 
    array (
      0 => '{:module}_{:action}/{$_SERVER.REQUEST_URI|md5}',
      1 => 3600,
    ),
  ),
  'player_width' => 610,
  'player_height' => 458,
  'player_down' => 'http://union.gxcms.com/app/player.php',
  'player_buffer' => 'http://www.84fun.com/temp/Banner/play-center.html',
  'player_pause' => 'http://union.gxcms.com/app/pause.html',
  'player_time' => '8',
);
?>
